server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shorturl
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update